apiVersion: v2
name: localpv-provisioner
description: Helm chart for OpenEBS Dynamic Local PV. For instructions to install OpenEBS Dynamic Local PV using helm chart, refer to https://openebs.github.io/dynamic-localpv-provisioner/.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 3.3.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.3.0
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - storage
  - local
  - dynamic-localpv
sources:
  - https://github.com/openebs/dynamic-localpv-provisioner

dependencies:
  - name: openebs-ndm
    version: "2.0.0"
    repository: "https://openebs.github.io/node-disk-manager"
    condition: openebsNDM.enabled

maintainers:
  - name: akhilerm
    email: akhil.mohan@mayadata.io
  - name: kiranmova
    email: kiran.mova@mayadata.io
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
